apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::989788463218:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::989788463218:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OPFGRGE0SKZ6
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-23T18:38:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1520"
  uid: 6e331cd1-9ccb-4a84-b181-bdbf4da48965
